events {}
http {
  resolver 127.0.0.11 valid=10s;

  server {
    listen 80;

    location /orders/ {
      set $upstream order-service:5000;
      rewrite ^/orders/(.*)$ /$1 break;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-ID $http_x_request_id;
      proxy_pass http://$upstream;
    }

    location /users/ {
      set $upstream user-service:5000;
      rewrite ^/users/(.*)$ /$1 break;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-ID $http_x_request_id;
      proxy_pass http://$upstream;
    }

    location /payments/ {
      set $upstream payment-service:5000;
      rewrite ^/payments/(.*)$ /$1 break;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-ID $http_x_request_id;
      proxy_pass http://$upstream;
    }

    location /inventory/ {
      set $upstream inventory-service:5000;
      rewrite ^/inventory/(.*)$ /$1 break;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-ID $http_x_request_id;
      proxy_pass http://$upstream;
    }

    location / {
      set $upstream frontend:5000;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Request-ID $http_x_request_id;
      proxy_pass http://$upstream;
    }
  }
}
